kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-default-consul-consul-server-0
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
